services:
    gravitlauncher:
        build:
            context: .
            dockerfile: Dockerfile.launcher
        restart: always
        stdin_open: true
        tty: true
        volumes:
        - launcher:/app/data
        environment:
            ADDRESS:
            PROJECTNAME:
    simplecabinet:
        build:
            context: .
            dockerfile: Dockerfile.simplecabinet
        restart: always
        stdin_open: true
        tty: true
        volumes:
        - assets:/app/assets
        depends_on:
            - postgres
    postgres:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_DB:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
        volumes:
            - postgres-database:/var/lib/postgresql/data
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        restart: always
        volumes:
            - launcher:/volume
            - assets:/assets
        ports:
            - 17549:80
        depends_on:
            - gravitlauncher
volumes:
    launcher:
    assets:
    postgres-database:
